// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerIdentity = {
/**
 * Unique identity for this process start.
 */
instanceId: string,
/**
 * Host lifecycle generation backed by an immutable package.
 */
generation: string,
/**
 * Exact source commit recorded by the package builder.
 */
sourceSha: string,
/**
 * Reviewed compatibility revision for rolling-generation behavior.
 */
protocolRevision: number,
/**
 * Rolling-generation behaviors supported by this server.
 */
capabilities: Array<string>, };
